#!/bin/sh

cd `dirname $0`

#------------------------------------------------------------------------------
# make the git repo accessible via:
#     git clone http://rtpgsa.ibm.com/~pmuellr/git-repos/coffeetalk/.git
#------------------------------------------------------------------------------

git update-server-info

rsync \
    --verbose \
    --archive \
    --exclude-from=.gitignore \
   . \
   rtpgsa.ibm.com:~/web/git-repos/shelley