# Licensed under the Tumbolia Public License. See footer for details.

buildAll:
	@echo "-> building `pwd`"
	@echo " " 
	@cd basic; make

buildOne:

	@echo "-> building `pwd`"

	@../../node_modules/.bin/coffee --compile *.coffee
	    
	@echo " " 

#-------------------------------------------------------------------------------
# Copyright (c) 2012 Patrick Mueller
# 
# Tumbolia Public License
# 
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and this
# notice are preserved.
# 
# TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
# 
#   0. opan saurce LOL
#-------------------------------------------------------------------------------
