// Generated by CoffeeScript 1.3.2
(function() {
  var main, openShell, shelley;

  shelley = require('shelley');

  main = function() {
    return $('#button-open-shell').click(openShell);
  };

  openShell = function() {
    var content, shell;
    content = $("<div>");
    content.html("<p>opened at: " + (Date()));
    content.addClass("green");
    shell = shelley.createShell({
      title: "closeable shell",
      element: content
    });
    return shell.open();
  };

  $(document).ready(main);

}).call(this);
