// Generated by CoffeeScript 1.3.2
(function() {
  var main, openCloseableShell, openModalShell, openUncloseableShell, shelley;

  shelley = require('shelley');

  main = function() {
    $('#button-open-closeable-shell').click(openCloseableShell);
    $('#button-open-uncloseable-shell').click(openUncloseableShell);
    return $('#button-open-modal-shell').click(openModalShell);
  };

  openCloseableShell = function() {
    var content, shell;
    content = $("<div>");
    content.html("<p>opened at: " + (Date()));
    shell = shelley.createShell({
      title: "closeable shell",
      element: content
    });
    return shell.open();
  };

  openUncloseableShell = function() {
    var content, shell;
    content = $("<div>");
    content.html("<p>opened at: " + (Date()));
    shell = shelley.createShell({
      title: "uncloseable shell",
      closeable: false,
      element: content
    });
    return shell.open();
  };

  openModalShell = function() {
    var shell;
    return shell = shelley.createShell({
      title: "modal shell",
      modal: true,
      element: $("#modal-shell")
    });
  };

  $(document).ready(main);

}).call(this);
